In [13]:
import numpy as np 
import gym

In [14]:
# load the environment
env = gym.make('FrozenLake-v0')

In [15]:
# Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])

# Set learning parameters
lr = .8
y = .95
num_episodes = 2000

# Create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    # Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j=0
    # The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        # Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        # Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [16]:
print("score over time: ", sum(rList)/num_episodes)

score over time:  0.547


In [17]:
print(Q)

[[2.37678095e-01 7.48251971e-03 1.26094983e-02 9.79182899e-03]
 [4.49138649e-04 9.19448875e-04 1.54723914e-03 3.44930595e-01]
 [1.58165672e-01 2.49998765e-03 8.48257034e-03 5.40993481e-03]
 [6.67139163e-03 1.75514330e-04 3.91964039e-03 4.71177382e-03]
 [5.21111445e-01 8.92691551e-04 7.25392218e-04 5.63836192e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.07559463e-05 3.56152097e-06 3.64441146e-02 6.36728228e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.41485538e-04 2.40908294e-03 1.19422402e-02 6.44430821e-01]
 [6.82328608e-03 3.21465483e-01 1.03254078e-03 2.14919069e-03]
 [7.61148627e-01 1.04966333e-03 3.01528928e-04 6.79883208e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.96966586e-03 1.66460357e-03 9.23459325e-01 2.37659273e-03]
 [0.00000000e+00 0.00000000e+00 9.82748706e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000

## Q-Learning in TF


In [19]:
import gym
import numpy as np
import random
import tensorflow as tf
import matplotlib.pyplot as plt
%matplotlib inline

/Users/haruyaishikawa/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/Users/haruyaishikawa/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [20]:
# load the env
env = gym.make('FrozenLake-v0')

#### The Q-Network Approach

In [21]:
tf.reset_default_graph()

In [23]:
# feed-forward part of the network used to choose actions
inputs1 = tf.placeholder(shape= [1,16], dtype=tf.float32)
W = tf.Variable(tf.random_uniform([16, 4], 0, 0.01))
Qout = tf.matmul(inputs1, W)
predict = tf.argmax(Qout, 1)

# loss: sum of squared difference between target and prediction Q values
nextQ = tf.placeholder(shape=[1,4],dtype=tf.float32)
loss = tf.reduce_sum(tf.square(nextQ - Qout))
trainer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
updateModel = trainer.minimize(loss)